### ISSUE TITLE
Linux Q4OS can only install v1.1.2

### ISSUE THREAD

**Issue by Snake221982** [leobrigassi/Time_Capsule_Proxy#27]
HI.
It doesn't install via script. When I run it, I get 
main: line 689: No such file or directory 
main: line 690: No such file or directory. 
This happens on both scripts.

**Comment by leobrigassi** [comment]
Hi, looks like a logging issue but I'm not able to reproduce. I just installed both main and the latest beta (beta was updated today) without errors.

Are you installing over previous install? clear the directory to avoid conflicts before retrying.

after a successful install, if you just want to pull the system up again or turn off you don't need to reinstall and you can just run:
./tcpoxy --up
./tcproxy --down

**Comment by Snake221982** [comment]
I am installing on another MacBook with Linux installed. This is a new installation. The script was not installed on this machine before. I reinstalled the system and still the same error

ra@macbookair61:~$ wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/main/tcproxy 2>/dev/null | STATS=0 bash
main: line 689: No such file or directory
main: line 690: No such file or directory.
ra@macbookair61:~$ wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/beta/tcproxy 2>/dev/null | BETA= bash
main: line 666 No such file or directory
main: line 667: No such file or directory.

**Comment by leobrigassi** [comment]
So it works on the previous system and not on the new one?
Can you share the details of your system? 

Try the beta I pushed this morning make sure curl is installed on your system:
sudo apt install curl

Have you tried installing an older release like 2.1.0 and see if you still have this issue?

**Comment by leobrigassi** [comment]
Also you can try to run the installation of the script locally:

`./tcproxy --install`

**Comment by Snake221982** [comment]
The latest version of curl package (7.88.1-10+deb12u6) is already installed. Look, there are two MacBooks. Model A1465. One is mine, the other is my friend's. I installed the script on mine a long time ago and with your help everything worked. I can't install it on my friend's laptop because of the error I described above. Both laptops have the Q4OS operating system.

**Comment by Snake221982** [comment]
ra@macbookair61:~$  wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/main/tcproxy 2>/dev/null | bash
main: line 689 No such file or directory
main: line 690: No such file or directory.
ra@macbookair61:~$  wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/beta/tcproxy 2>/dev/null | BETA= bash
main: line 666 No such file or directory
main: line 667: No such file or directory.
ra@macbookair61:~$ wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/main/tcproxy 2>/dev/null | STATS=0 bash
main: line 689 No such file or directory
main: line 690: No such file or directory.
ra@macbookair61:~$

**Comment by leobrigassi** [comment]
You are installing again the latest version. 

Try an older release such as v2.1.0 or even the one that worked for you on your other laptop v1.1.2

Did the local installation also fail ?

**Comment by Snake221982** [comment]
Sorry, where can I get version 1.1.2?

**Comment by leobrigassi** [comment]
https://github.com/leobrigassi/time-capsule-proxy/releases

**Comment by Snake221982** [comment]
> https://github.com/leobrigassi/time-capsule-proxy/releases

Installed and worked great. Thank you. Apparently this version is just for MacBooks 😁

**Comment by leobrigassi** [comment]
So which one worked in the end?
I suggest you try install the latest possible version as the earlier versions were a bit buggy

**Comment by Snake221982** [comment]
> So which one worked in the end?

1.1.2 
Ill try to install the new versions again now

**Comment by Snake221982** [comment]
New versions didn't start. Deleted everything. I reinstalled version 1.1.2 and now I get: Load key “./id_rsa_vm”: Permission denied Permission denied (Publi ley, keyboard-interactive)

**Comment by leobrigassi** [comment]
Oh I see. 

You probably didn’t switch off the VM before installing the new version and now it’s conflicting. 

Delete the whole thing, folder included and reboot before re-installing.

**Comment by Snake221982** [comment]
I tried to install new versions on an old IMac with Linux installed and got exactly the same errors. It turns out that the script version 1.1.2 works fine on Mac and IMac, and scripts starting from version 2.0 and higher, all get the error

main: line 666 No such file or directory
main: line 667: No such file or directory.

and

main: line 689 No such file or directory
main: line 690: No such file or directory.

**Comment by leobrigassi** [comment]
Thanks for this. 
I think the problem lies in the fact that on Q4OS you might be missing some basic packages that are standard on most other distros and so it fails creating or writing to the log file. I've created a build which explicitly verifies also standard packages for missing dependencies and double checks if the log files actually gets created. 
If any packages are missing it should list the missing ones so then you can install them with:

sudo apt install package1 package2 ...

`wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/dev/tcproxy 2>/dev/null | DEV= bash`

can you test this out and see if it then works?

**Comment by Snake221982** [comment]
> Thanks for this. I think the problem lies in the fact that on Q4OS you might be missing some basic packages that are standard on most other distros and so it fails creating or writing to the log file. I've created a build which explicitly verifies also standard packages for missing dependencies and double checks if the log files actually gets created. If any packages are missing it should list the missing ones so then you can install them with:
> 
> sudo apt install package1 package2 ...
> 
> `wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/dev/tcproxy 2>/dev/null | DEV= bash`
> 
> can you test this out and see if it then works?

ra@macbookair61:~$ wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/dev/tcproxy 2>/dev/null | DEV= bash
All required dependencies are installed.

**Comment by leobrigassi** [comment]
And still does not install?

You should have at least have a log file now in the directory so you can check for any specific error. 

`cat log-tcproxy.txt`


Also if the script run you should have the file tcproxy in the folder. 

You can run:
`./tcproxy --install`

If you run this command it should send your logs to the server so I can check your logs remotely:
`./tcproxy --remote-log`


No file? Download it directly with this link:

`wget https://github.com/leobrigassi/time-capsule-proxy/raw/92208874e1f3d071fe4b0bdb23d051605568deb3/tcproxy && chmod +x tcproxy`

**Comment by Snake221982** [comment]
ra@macbookair61:~$ wget https://github.com/leobrigassi/time-capsule-proxy/raw/92208874e1f3d071fe4b0bdb23d051605568deb3/tcproxy && chmod +x tcproxy
--2024-08-26 18:26:56-- https://github.com/leobrigassi/time-capsule-proxy/raw/92208874e1f3d071fe4b0bdb23d051605568deb3/tcproxy
Recognized by github.com (github.com)… 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connection established.
The HTTP request has been sent. Waiting for a response... 302 Found
Address: https://raw.githubusercontent.com/leobrigassi/time-capsule-proxy/92208874e1f3d071fe4b0bdb23d051605568deb3/tcproxy [transition]
--2024-08-26 18:26:57-- https://raw.githubusercontent.com/leobrigassi/time-capsule-proxy/92208874e1f3d071fe4b0bdb23d051605568deb3/tcproxy
Recognized by raw.githubusercontent.com (raw.githubusercontent.com)… 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connection established.
The HTTP request has been sent. Waiting for a response... 200 OK
Length: 42628 (42K) [text/plain]
tcproxy: This is a directory

Cannot write to "tcproxy" (This is a directory).




ra@macbookair61:~$ cat log-tcproxy.txt
cat: log-tcproxy.txt: No such file or directory

**Comment by leobrigassi** [comment]
You need to go into the directory first 😉
`cd tcproxy`

**Comment by Snake221982** [comment]
Sent remote log. I just don’t understand the meaning of these actions. I have an old version of the script installed. I can’t install a new one because of the errors that I mentioned above

ra@macbookair61:~/tcproxy$ ./tcproxy --install
All required dependencies are installed.
ra@macbookair61:~/tcproxy$ ./tcproxy --remote-log
All required dependencies are installed.

**Comment by leobrigassi** [comment]
If you have no clue what these commands are for then I suggest you stick to the version that works for you. 
Unfortunately though if I don't understand where the issue is I won't be able to help you run the latest versions. 
Hope that the older version works for you well! All the best!

**Comment by Snake221982** [comment]
I didn't express myself quite correctly. What I meant is that I have an old version of the script installed. And accordingly, the log will be from the old version. or am I wrong? After all, in order to get a log with a problem, you need to install a new script? But it doesn't install

**Comment by leobrigassi** [comment]
What I mean is that without some debugging data I cannot really guess what is going wrong on your system and I don't want to bore you in running weird debugging commands you might not fully understand. 

In your last try I didn't receive any logs on the server so it also didn't work. 
You can send me your local logs (if there are any) and I can have another try to figure this out. 

If not, at least you have a working script and hopefully this is good enough for you!

**Comment by Snake221982** [comment]
[log-tcproxy.txt](https://github.com/user-attachments/files/16752035/log-tcproxy.txt)

**Comment by leobrigassi** [comment]
From the logs looks like your system is working correctly and you also have the latest version installed? 

`./tcproxy --version`

If you can access your files then happy days 😉

**Comment by Snake221982** [comment]
ra@macbookair61:~/tcproxy$ ./tcproxy --version
All required dependencies are installed.

That's the point. Everything works well, but the script version is 1.1.2 )))))


The easiest option is apparently to use Anydesk. Because you don’t see the error in the logs that I send. I have a clean clean system, so if you are interested, you can try remotely via anydesk to see what the problem is

**Comment by leobrigassi** [comment]
Sure happy to have a look. 
Send me and email so we can take it off the forum

**Comment by Snake221982** [comment]
The problem is solved.
The script works for MacBook Air with the installed Q4OS operating system.
The only point is after rebooting the laptop, the script needs to be launched manually.
Thank you so much for your help and good day )))

**Comment by leobrigassi** [comment]
Great thanks for the feedback. It was good to debug together yesterday. Thanks for your time and happy it now works.
