### ISSUE TITLE
mount error(111): could not connect to 192.168.1.165Unable to find suitable address.

### ISSUE THREAD

**Issue by Harry99a** [leobrigassi/Time_Capsule_Proxy#56]
Hallo Leo,
your project is great, because I was searching for some code to use my old Time Capsule for years now.
But I have a problem. See here:
`harald@ESPRIMO:~$ wget -O - https://github.com/leobrigassi/time_capsule_proxy/raw/beta/tcproxy 2>/dev/null | BETA= bash
[INFO] Installation not detected. Run [./tcproxy --install] to setup your system.
GNU tcproxy: mount Time Capsule / AirPort Extreme on debian kernels 5.15+.
tcproxy v2.1.5_a4: [ bash ] Installing...

Downloading latest installation script...
Downloading tcproxy suite from server...
Initiating umount routine...
Host umount routine of all specified mount points completed.
VM detected. Sending poweroff command...
VM powered down...
VM down... attempting to load...
VM launched...
Waiting for VM to boot...
VM up...
Provisioning VM...
mount error(111): could not connect to 192.168.1.165Unable to find suitable address.
mount: mounting //192.168.1.165/TC_Data on /mnt/tc/TC_Data failed: Invalid argument
[ERROR] VM unable to mount to Time Capsule folder 192.168.1.165/TC_Data. Please check credentials, IPv4 or connectivity and run again.`

I can ping 192.168.1.165, so the IP-adress of my time capsule is OK.

I use the following machine:
System:
  Kernel: 5.15.0-122-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: FUJITSU product: ESPRIMO E910 v: N/A serial: <superuser required> Chassis:
    type: 3 v: C$EKW1 serial: <superuser required>
  Mobo: FUJITSU model: D3162-A1 v: S26361-D3162-A1 serial: <superuser required>
    UEFI: FUJITSU // American Megatrends v: 4.6.5.3 R1.19.0 for D3162-A1x date: 12/17/2012
CPU:
  Info: quad core model: Intel Core i5-3470 bits: 64 type: MCP smt: <unsupported> arch: Ivy Bridge
    rev: 9 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3471 high: 3493 min/max: 1600/3600 cores: 1: 3493 2: 3462 3: 3470 4: 3460
    bogomips: 25543
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx

Can you help me with this issue? I don't know, where to start.

Thank you very much in advance, Harry

**Comment by leobrigassi** [comment]
Hey Harry,
Looks like credentials or IP address are at play here. 
Open airport utility and make sure the up address is correct and credentials are indeed correct. 

If you are protecting only with device password no username must be inserted. 

Also the name of the shared disk seems strange. The standard one is "Data" unlike what you have typed "TC_Data". So if you have not changed the disk name manually give it another try with just "Data". 

Also reboot all your devices i.e. both server and time capsule before retrying. Sometimes the time capsule is a bit sensitive to multiple failed attempts ;)

Hope it helps!

**Comment by Harry99a** [comment]
Hey Leo!
Thank you very much for your help. I just found the failure:
My password for the TimeCapsule was **12312399** --> this was **too weak!**
I changed it to **Something99$** (not my real PW ;-) but now it works like charm!

Thank you very much!

Yours, Harry

**Comment by leobrigassi** [comment]
My pleasure 😉
Happy to hear it’s now working fine! Enjoy!
